default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 172.17.0.1
  port: 5432
  username: root
  password: root

development:
  <<: *default
  database: TesteDevNobordist_development

test:
  <<: *default
  database: TesteDevNobordist_test

production:
  <<: *default
  password: <%= ENV['TESTEDEVNOBORDIST_DATABASE_PASSWORD'] %>
